version: 1
disable_existing_loggers: False

formatters:
  standard:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
    
  detailed:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(module)s - %(funcName)s:%(lineno)d - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
    
  json:
    format: '{"timestamp": "%(asctime)s", "logger": "%(name)s", "level": "%(levelname)s", "module": "%(module)s", "function": "%(funcName)s", "line": %(lineno)d, "message": "%(message)s"}'
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout
    
  file_info:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: standard
    filename: logs/info.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf-8
    
  file_debug:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: logs/debug.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf-8
    
  file_error:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: detailed
    filename: logs/error.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf-8
    
  model_performance:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: json
    filename: logs/model_performance.log
    maxBytes: 10485760  # 10MB
    backupCount: 10
    encoding: utf-8
    
  data_drift:
    class: logging.handlers.RotatingFileHandler
    level: WARNING
    formatter: json
    filename: logs/data_drift.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf-8

loggers:
  # Root logger
  root:
    level: INFO
    handlers: [console, file_info, file_error]
    propagate: no
    
  # Application specific loggers
  src.data_processing:
    level: DEBUG
    handlers: [console, file_debug]
    propagate: no
    
  src.modeling:
    level: DEBUG
    handlers: [console, file_debug, model_performance]
    propagate: no
    
  src.feature_engineering:
    level: DEBUG
    handlers: [console, file_debug]
    propagate: no
    
  pipelines:
    level: INFO
    handlers: [console, file_info]
    propagate: no
    
  api_service:
    level: INFO
    handlers: [console, file_info]
    propagate: no
    
  monitoring:
    level: WARNING
    handlers: [console, file_error, data_drift]
    propagate: no
    
  # Third-party libraries
  uvicorn:
    level: INFO
    handlers: [console]
    propagate: no
    
  fastapi:
    level: INFO
    handlers: [console]
    propagate: no
    
  sqlalchemy:
    level: WARNING
    handlers: [file_error]
    propagate: no
    
  mlflow:
    level: WARNING
    handlers: [file_error]
    propagate: no 